# GitHub Pages Configuration for World Leaders Game Documentation
title: "World Leaders Game"
tagline: "AI-Led Educational Development"
description: "A father-son experiment in AI autonomy for educational software development - transforming a 12-year-old's voice memo into a production-ready game using 95% AI guidance."

# Site settings
url: "https://victorsaly.github.io"
baseurl: "/WorldLeadersGame"

# Author information
author:
  name: "Victor & Oliver Saly"
  email: "info@victorsaly.com"
  twitter_username: victorsaly
  github_username: victorsaly

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Override minima theme to create Chirpy-inspired design
minima:
  skin: dark

# Site logo/avatar
logo: '/assets/world-leaders-logo.svg'

# Theme settings inspired by Chirpy
chirpy_inspired:
  theme_mode: auto  # [light|dark|auto]
  sidebar:
    avatar: '/assets/world-leaders-logo.svg'

# Essential plugins compatible with GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Social links
social:
  name: "Victor & Oliver Saly"
  email: "info@victorsaly.com"
  links:
    - https://github.com/victorsaly
    - https://twitter.com/victorsaly

# Google Analytics (you can add your GA ID later)
google_analytics: ''

# Navigation
header_pages:
  - index.md
  - blog.md
  - technical-docs.md
  - journey.md
  - about.md

# Collections for better organization
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  journey:
    output: true
    permalink: /journey/:name/
  technical:
    output: true
    permalink: /technical/:name/
  milestones:
    output: true
    permalink: /milestones/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Victor Saly"
  - scope:
      path: ""
      type: "journey"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "technical"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "milestones"
    values:
      layout: "page"

# Social links
github_username: victorsaly
linkedin_username: victorsaly

# Google Analytics (optional)
# google_analytics: YOUR_GA_TRACKING_ID

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - vendor/bundle
  - src/
  - .vscode/
  - start-game.sh
  - README.md
